### PR TITLE
fix(deepExtend): Ensure dest is obj when src is obj

### PR DESCRIPTION
**Pull request by TheSharpieOne**
currently `deepExtend` is not ensuring the `destination` is an object when the source is an object.
`deepExtend` currently does a [similar check/set for the case of `source` being an array](https://github.com/pablojim/highcharts-ng/blob/a874fdd0d7ca0c40abbfe13e8e3c00f7490c6f8b/src/highcharts-ng.js#L109).
This PR adds the check for `destination` being an object and if not sets it to `{}`.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
This fixes #367

**Comment by brandonrobertz** [comment]
We need a unit test on this IMO

**Comment by TheSharpieOne** [comment]
Tests added for this case, but for a method such as `deepExtend`... it is seriously lacking tests to the point where adding just this one is almost pointless.

**Comment by brandonrobertz** [comment]
Is there a reason we're not using angular.merge?

**Comment by TheSharpieOne** [comment]
idk, I didn't make this thing, just trying to fix it.

**Comment by brandonrobertz** [comment]
@TheSharpieOne Good idea about the PR. In the meantime I think your fix is good for now. I'm locked at 0.0.8 until I can trust this lib to not break me with a semver patch-version number update.

**Comment by pablojim** [comment]
Thanks @TheSharpieOne  and @brandonrobertz.

**Comment by pablojim** [comment]
angular.merge did not exists when this package was written. Switching to it now seems to make sense.

**Pull request merged**
