### PR TITLE
added support for $onChanges, added new binding to disable change detection

### PR DESCRIPTION
**Pull request by ngehlert**
like discussed in #621 I added support for $onChanges and the new disableChangeDetection binding.
a little side not: due the nature of $onChanges being called before $onInit but the DOM not rendered at this point of time I still kept support for $onInit. So everything stays the same, I just added the $onChanges method to support later changes. A flag if the $onInit was already called is needed for this.

Should I also update the documentation?
Let me know if you have any questions.

### CODE REVIEW

**Comment by pablojim** [comment]
@ngehlert Looks good so far if you could add something to the docs and add a jsfiddle example to the examples directory then I'd be happy to merge.

Thanks!

**Comment by ngehlert** [comment]
@pablojim i updated the readme. not quite sure how i should add a jsfiddle since it is not merged yet. 
should i use my repository as lib endpoint? should i build it against the current master version, but then you can't test it before the merge? or should i add them in a separate PR after this one is complete?
maybe you have a better idea 🤔 😄

**Comment by pablojim** [comment]
@ngehlert Thanks. I've merged that. If you get a chance to make a jsfiddle and link to it from the readme that would be great.

**Comment by ngehlert** [comment]
@pablojim ok awesome. one last question regarding the jsfiddle. do i just create/update an example there and hit save? i saw that you have a separate directory with jsfiddle files. how does this work?

**Comment by pablojim** [comment]
So http://jsfiddle.net/gh/get/jquery/3.1.1/pablojim/highcharts-ng/tree/master/jsfiddles/basic/ 

This gets the html, js and "details" from:
https://github.com/pablojim/highcharts-ng/tree/master/jsfiddles/basic

It means we can manage the source of example jsfiddles in github. This is prefereable to just creating one in jsfiddle itself.

**Comment by ngehlert** [comment]
ok, didn't know that. thanks. this is actually a nice feature 😄  going to add the examples then

**Comment by ngehlert** [comment]
@pablojim sorry to bother you again. do you have any plans for the release date? is there any other issue / pr you want to have in there as well and need some help with?

**Comment by pablojim** [comment]
@ngehlert planning to do a release once #623 is dealt with.

**Pull request merged**
