### PR TITLE
First version of 0.1.0

### PR DESCRIPTION
**Pull request by pablojim**
- Now supports vanilla highcharts config
- Much less code - should be much more stable and less bugs
- Only support Highchart/Highstock >= 5.0.0
- 2-way axes binding no longer supported
- loading property no longer supported

### CODE REVIEW

**Comment by graingert** [comment]
probably worth killing support for Angular <= 1.5 and start to use a component instead

**Comment by pablojim** [comment]
@graingert good idea - will look into it.

**Comment by graingert** [comment]
@pablojim you can point 1.3 users at https://github.com/toddmotto/angular-component

**Comment by graingert** [comment]
probably also worth looking at babel for the source code.

**Comment by VictorioBerra** [comment]
Anyone using this in production yet? How stable would you guys say this is?

**Comment by pablojim** [comment]
@VictorioBerra in general it's a lot simpler than the original version so I'd expect it to be more stable. That said it is new and I'm pushing quite large changes still!

**Comment by VictorioBerra** [comment]
@pablojim do you have any idea of a time-frame on merging the beta to master?

**Comment by graingert** [comment]
@pablojim any chance of including a function in your documentation to convert the old style object into the new?

**Comment by VictorioBerra** [comment]
@graingert  there is no new style object. It takes a normal highcharts object. Just remove your "option" property and move everything inside it out to the config object.

**Comment by Stenkilde** [comment]
I'm not sure if I'm an idiot, but can we include an example of how to use the drilldowns?
As the whole config structure, it might be worth it to bring an example for this for new comers?

**Comment by VictorioBerra** [comment]
@Stenkilde Im not sure whats so confusing about this new version for people. Because @graingert was also asking about the "new config structure".

The configuration object is now IDENTICAL to the same one you would normal pass to your Highcharts constructor.  If you want to use drilldowns. Head over to the [official highcharts documentation here](http://api.highcharts.com/highcharts/drilldown) and use their [example drilldown configuration](http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/drilldown/basic/). **NOTE:** [**Make sure to include the drilldown plugin.**](http://code.highcharts.com/modules/drilldown.js)

[I have created a jsfiddle for you that demonstrates the use of drilldowns uses highcharts-ng2. Notice how the configuration object I pass to highcharts-ng2 is a copy/paste of the one from the official highcharts example I linked above.](http://jsfiddle.net/Lord_Zero/LnkgL135/5/)

**Comment by graingert** [comment]
@VictorioBerra I've never used the normal Highcharts constructor.

**Comment by graingert** [comment]
@VictorioBerra @pablojim is this what you mean?

```js
function convertOldHighchartsNgToNew({ options, config }) {
    return Object.assign({}, config, options);
}
```

**Comment by VictorioBerra** [comment]
If you really need that, then yes that will work. Id recommend running a
conversion script against your saved configuration data using that instead
of hard coding it as a permanent conversion operation in your database.
Otherwise you will need stuff like `if(config.options !== undefined)` after
you start persisting your new config.

**Comment by graingert** [comment]
@VictorioBerra our config is generated on the fly, I just didn't understand the changes to make.

**Comment by VictorioBerra** [comment]
@graingert No worries. In general now that this library accepts a [regular highcharts config object](http://api.highcharts.com/highcharts/) it will be much simpler to use and configure. Now you can just use the HC docs and know that this library will work out of the box.

**Comment by graingert** [comment]
@pablojim @VictorioBerra what was the "2-way axes binding" because it's "no longer supported"?

**Comment by pablojim** [comment]
@Stenkilde no silly questions - let us know if @VictorioBerra's jsfiddle doesn't work for you!

@VictorioBerra Thanks for providing the example jsfiddle - maybe we can automate the creation of these!

@graingert don't think I'll provide a conversion function as there are some subtleties around events and other config that might be hard to support.

The 2-way axis binding is where you previously could zoom in in the chart and have the config update to reflect the new axis values. This is no longer supported as I'm trying to move the component to a one way binding. Axes changes could be notified by events but this is not implemented yet.

**Comment by benck** [comment]
"The chart does not fit into the parent container? How to fix that?" in the FAQ does not apply for the beta version. How could I fix this in the beta version?

**Comment by VictorioBerra** [comment]
Legend title bug with series IDs. https://jsfiddle.net/Lord_Zero/xkdk91mg/

Notice how there is no legend title. If you uncomment the ids in the config the title works.

The library should be ensuring IDs.

**Pull request merged**
