### PR TITLE
 remove standalone lazyLoad Fixes #487 

### LINKED ISSUE #487: drop standalone lazyLoad and documentation
standalone-framework is built in. jQuery is not used at all.

https://github.com/highcharts/highcharts/blob/master/js/adapters/standalone-framework.src.js is now 0 bytes.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by pablojim** [comment]
Maybe just update the comment to state for what versions of highcharts this is applicable.

**Comment by graingert** [comment]
@pablojim well lazyLoad will load the latest highcharts every time...

**Comment by pablojim** [comment]
@graingert sure, but not all users will be using lazy loading.

**Comment by graingert** [comment]
@pablojim updated

**Comment by pablojim** [comment]
thanks @graingert

**Pull request merged**
