### PR TITLE
Update highcharts-ng.js

### PR DESCRIPTION
**Pull request by lwallent**
Hi @rafaelmacario and @pablojim

This PR will fix a bug introduced in fixing issue #592 (please see my comments to that issue)

KR 
Lasse

### CODE REVIEW

**Comment by pablojim** [comment]
@lwallent Thank you!

**Comment by lwallent** [comment]
Hi @pablojim,
 
Any chance that my change will be released to the npm repository in the near future?
That way I can keep my dependencies simple 👍  (and the current npm version fails when importing)
Thanks for the great work!

KR

Lasse

**Comment by Boosten** [comment]
@pablojim a new release would be helpful :)

**Comment by andrewboni** [comment]
@lwallent thank you! I also encountered this same issue and spent a lot more time than I'd have liked trying to resolve

@pablojim gentle bump on a new release :)

**Pull request merged**
