### PR TITLE
fix(highstock) : require highstock instead of highcharts

### PR DESCRIPTION
**Pull request by houssemba**
- require highstock which include highcharts and highmaps
   - fix es6 import when we need highstock

### CODE REVIEW

**Comment by houssemba** [comment]
@pablojim is it possible to merge this PR and release please ?

**Comment by pablojim** [comment]
Many users will only have the license for highcharts and not for highstocks. IS there a way to handle this?

**Comment by houssemba** [comment]
Thank you for your answer.
I think that there is no problem concerning license (if you only use highcharts feature ?)

What do you think ?

**Comment by pablojim** [comment]
@houssemba  Thanks!

**Comment by npetralia** [comment]
Hello,

I am sorry but there is an issue with the licence if you include highstock and you pay only for highmaps. It is 3 differents products. For non commercial use it is not an issue, but for commercial use it is a problem.

The correct way of doing is this : https://www.highcharts.com/docs/getting-started/installation

If stock or maps are required in the same page as each other or with basic Highcharts, they can be loaded as modules:
<script src="/js/highcharts.js"></script>
<script src="/js/modules/stock.js"></script>
<script src="/js/modules/map.js"></script>

3 cases:
You pay only for highmaps you must have
<script src="/js/highmaps.js"></script>

You pay only for highstock you must have
<script src="/js/highstock.js"></script>

You pay for 2 or 3 products:
<script src="/js/highcharts.js"></script>
<script src="/js/modules/stock.js"></script>
<script src="/js/modules/map.js"></script>

**Pull request merged**
