### PR TITLE
fix(resize) : fix resizing bug with bootstrap and angular material

### LINKED ISSUE #550: Resizing to screen size
After updating to latest version the resizing to screen size is not working with normal bootstrap.css
## Expected Behaviour

The chart in previous versions resizes according to screen size using typical bootstrap.css
After latest update, it only resizes if using bootstrap-combined.css

## Current Behaviour

Resizing is not working
## Steps to Reproduce & Link to Example 

1. http://jsfiddle.net/pablojim/LnkgL135/
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by houssemba**
fix #550

### CODE REVIEW

**Comment by pablojim** [comment]
@houssemba Looks good.

Any chance you would add a reference to the css in the README? And a jsfiddle  to the demos folder if you are feeling really helpful!

**Comment by lodrantl** [comment]
I think the element name in CSS is highchart and not highcharts.

**Comment by houssemba** [comment]
Done ! I updated the readme and added a jsfiddle
Thanks guys

**Comment by pablojim** [comment]
@houssemba @lodrantl Thanks!

**Pull request merged**
